### ISSUE TITLE
npm test failed

### ISSUE THREAD

**Issue by leizh1984** [IBM/BlockchainNetwork-CompositeJourney#1]
root@ubuntu:~/BlockchainNetwork-CompositeJourney# npm test --unsafe-perm

> my-network@0.0.1 test /root/BlockchainNetwork-CompositeJourney
> mocha --recursive

  Commodity Trading
    1) "before all" hook

  0 passing (2s)
  1 failing

  1) Commodity Trading
       "before all" hook:
     AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#admin' does not have 'READ' access to resource 'org.hyperledger.composer.system.Network#my-network@0.0.1'
      at aclRules.reduce.then (node_modules/composer-runtime/lib/accesscontroller.js:134:23)
      at process._tickCallback (internal/process/next_tick.js:109:7)

npm ERR! Test failed.  See above for more details.

**Comment by ishangulhane** [comment]
@leizh1984 I have updated the permissions file. Please try to run the code with updated permissions file.

**Comment by srinimf** [comment]
"NPM Test" command failing with error

![image](https://user-images.githubusercontent.com/38401782/49696788-42ac6400-fbd5-11e8-9470-2bcb65157f08.png)

**Comment by giltachy** [comment]
NPM test failed with below error

> my-network@0.0.1 test /home/nodejs/BlockchainNetwork-CompositeJourney
> mocha --recursive



  Commodity Trading
    1) "before all" hook in "Commodity Trading"


  0 passing (3s)
  1 failing

  1) Commodity Trading
       "before all" hook in "Commodity Trading":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/nodejs/BlockchainNetwork-CompositeJourney/test/sample.js)
  



npm ERR! Test failed.  See above for more details.
