### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by hossamsamy007** [IBM/BlockchainNetwork-CompositeJourney#11]
npm test

> my-network@0.0.1 test /root/BlockchainNetwork-CompositeJourney
> mocha --recursive

  Commodity Trading
    1) "before all" hook

  0 passing (106ms)
  1 failing

  1) Commodity Trading
       "before all" hook:
     TypeError: adminConnection.createProfile is not a function
      at Context.before (test/sample.js:36:32)

npm ERR! Test failed.  See above for more details.

**Comment by ljbennett62** [comment]
@hossamsamy007 - try it now as the pattern has been updated to V1.1 and it works all the way through.
