### ISSUE TITLE
Error on "composer network deploy"

### ISSUE THREAD

**Issue by Bataahai** [IBM/BlockchainNetwork-CompositeJourney#3]
Hi,

I'm at the step 5 (Deploy the Business Network Archive on Hyperledger Composer running locally).
When I execute the following command it gives an error "Missing argument value: networkAdminEnrollSecret"

composer network deploy -a my-network.bna -p hlfv1 -i PeerAdmin -s randomString -A admin -S

Then I added a string for the missing value as below

composer network deploy -a my-network.bna -p hlfv1 -i PeerAdmin -s randomString -A admin -S mypassword

But it fails with error "Unknown arguments: p, i, s".

Thank you all

**Comment by ishangulhane** [comment]
@Bataahai I have updated the instructions for the latest version of Hyperledger composer. Please try again.

**Comment by Bataahai** [comment]
Updated instruction is ok now.
Thank you!
