### ISSUE TITLE
 TypeError: adminConnection.createProfile is not a function

### ISSUE THREAD

**Issue by tung0811** [IBM/BlockchainNetwork-CompositeJourney#9]
Hi !! help me
npm test

> my-network@0.0.1 test /root/BlockchainNetwork-CompositeJourney
> mocha --recursive

  Commodity Trading
    1) "before all" hook

  0 passing (142ms)
  1 failing

  1) Commodity Trading
       "before all" hook:
     TypeError: adminConnection.createProfile is not a function
      at Context.before (test/sample.js:36:32)

**Comment by ljbennett62** [comment]
@tung0811 - try it now as the pattern has been updated to HPL V1.1 and it works all the way through.
